NNCodeTest/force-app/main/default/objects/API_Country__c/API_Country__c.object-meta.xml
<CustomObject>
    <label>API Country</label>
    <nameField>
        <label>API Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Regional Blocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/classes/Schedule_CheckAPIUpdate_Test.cls
@isTest
public class Schedule_CheckAPIUpdate_Test {
    
    public static String CRON_EXPRESSION = '0 0 0 15 3 ? 2042';
    
    @testSetup
    static void setup() {
        
        API_Country__c germanyDataTest = new API_Country__c();
        
        germanyDataTest.Name = 'Germany';
        germanyDataTest.Alpha_2_Code__c = 'DE';
        germanyDataTest.Alpha_3_Code__c = 'DEU';
        germanyDataTest.Capital_City__c = 'Berlin';
        germanyDataTest.Region__c = 'Europe';
        germanyDataTest.Regional_Blocs__c = 'EU';
        
        insert germanyDataTest;
        
        API_Country__c afghanistanDataTest = new API_Country__c();
        
        germanyDataTest.Name = 'Afghanistan';
        germanyDataTest.Alpha_2_Code__c = 'AF';
        germanyDataTest.Alpha_3_Code__c = 'AFG';
        germanyDataTest.Capital_City__c = 'Kabul';
        germanyDataTest.Region__c = 'Asia';
        germanyDataTest.Regional_Blocs__c = 'SAARC';
        
        insert afghanistanDataTest;
        
    }
    
    @IsTest
    static void testScheduledJob() {
        
        Test.setMock(HttpCalloutMock.class, new CheckAPIUpdate_Test_CalloutMock());
        
        Test.startTest();
        
        	Schedule_CheckAPIUpdate scheduleCheckAPIUpdate = new Schedule_CheckAPIUpdate();
        
            String jobId = System.schedule('Schedule Check API Update', CRON_EXPRESSION, scheduleCheckAPIUpdate);
        
        Test.stopTest();
        
        List<API_Country__c> apiCountryList = new List<API_Country__c>();
        apiCountryList = [SELECT Id, Name, Alpha_2_Code__c, Alpha_3_Code__c, Capital_City__c, Region__c, Regional_Blocs__c 
								  FROM API_Country__c];
        
        System.assertEquals(2, apiCountryList.size());
        
    }
}