NNCodeTest/force-app/main/default/objects/API_Country__c/API_Country__c.object-meta.xml
<CustomObject>
    <label>API Country</label>
    <nameField>
        <label>API Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/API_Country__c/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Regional Blocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/Lead/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <label>Alpha 2 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/Lead/fields/Alpha_3_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_3_Code__c</fullName>
    <label>Alpha 3 Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/Lead/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/Lead/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/objects/Lead/fields/Regional_Blocs__c.field-meta.xml
<CustomField>
    <fullName>Regional_Blocs__c</fullName>
    <label>Regional Blocs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NNCodeTest/force-app/main/default/classes/Trigger_Lead_APICountryDetails_Test.cls
@isTest
public class Trigger_Lead_APICountryDetails_Test {
    
    @testSetup 
    static void setup() {
        
        API_Country__c germanyDataTest = new API_Country__c();
        
        germanyDataTest.Name = 'Germany';
        germanyDataTest.Alpha_2_Code__c = 'DE';
        germanyDataTest.Alpha_3_Code__c = 'DEU';
        germanyDataTest.Capital_City__c = 'Berlin';
        germanyDataTest.Region__c = 'Europe';
        germanyDataTest.Regional_Blocs__c = 'EU';
        
        insert germanyDataTest;
        
    }
    
    @isTest
      static void testInsertLead() {
          
          Lead leadToInsert = new Lead(
              FirstName='Laura',
              LastName='Rogers',
              Company='Germany Company',
              Country='Germany'
          );
          
          Test.startTest();
          	insert leadToInsert;
          Test.stopTest();
          
          Lead updatedLead = [SELECT FirstName, Country_Name__c, Alpha_2_Code__c, Alpha_3_Code__c, Capital_City__c, Region__c, Regional_Blocs__c
                              FROM Lead
                              WHERE FirstName = 'Laura'];
          
          System.assertEquals('Laura', updatedLead.FirstName);        
          System.assertEquals('Germany', updatedLead.Country_Name__c);
          System.assertEquals('DE', updatedLead.Alpha_2_Code__c);
          System.assertEquals('DEU', updatedLead.Alpha_3_Code__c);
          System.assertEquals('Berlin', updatedLead.Capital_City__c);
          System.assertEquals('Europe', updatedLead.Region__c);
          System.assertEquals('EU', updatedLead.Regional_Blocs__c);
          
          
      }

}